### ISSUE TITLE
Poor transformer performance

### ISSUE THREAD

**Issue by Player3324** [hea3ven/HardModeTweaks#2]
I've noticed unusually slow loading times in a MC installation I've received for unrelated reasons. 

Sampler's startup profiling shows that the HardModeTweaks class transformer dominates class loading. The 3 hot spots in com.hea3ven.tools.mappings.Mapping alone use ~43% of the total startup time (255s).

Modded MC loads very large quantities of classes, ~34k in this instance. Transformers shouldn't do much more than a hardcoded equals check or a hashmap lookup to decide if a class is worth analyzing. Touching many classes or even every one is hardly ever worth the overhead.

A VisualVM compatible snapshot showing the problem is available at http://files.player.to/tmp/startup_hardmodetweaks.nps

**Comment by hea3ven** [comment]
Yes, thank you for reminding me, I need to rework the class name matching.
