### ISSUE TITLE
Feature Suggestion: harder to mine stone

### ISSUE THREAD

**Issue by K4N0** [hea3ven/HardModeTweaks#3]
If possible make stone take longer to mine. I have such fast mining tools that players can insta break like 20 blocks a sec with an atomic disassembler. Ores can remain the same mining speed or made even harder, but all i really need is stone to be much harder to mine. You can still use the normal tools to mine stone or remove stone and wood tools from being able to mine it.

**Comment by hea3ven** [comment]
I dunno how useful it would be, I've never used it, but acording to the documentation I found, the atomic disassembler is way faster than regular tools. If you were to reduce the mining speed to make it balanced, then the rest of the tools would take for ever to break anything. I don't know if it would be possible, but I'll try to see if you can enforce a max mining speed, that'll probably be more useful.

**Comment by K4N0** [comment]
Sounds Great, Thanks for the quick reply.
Can't wait to test it.

**Comment by K4N0** [comment]
Freaking Nice!!
