### ISSUE TITLE
Leaf blocks not solid

### ISSUE THREAD

**Issue by K4N0** [hea3ven/HardModeTweaks#4]
I disabled the config so that leaf blocks are solid. I am still falling thru the leaves 
B:enableNonSolidLeaves=false

it doesn't seem to be working to disable that option.

I restarted the server, now i'm glitching every time i touch a leaf block.
It is a preloaded world. Client and server configs are the same.
I have tried with a clean install and i'm still glitching out really bad while trying to walk on leaves.

**Comment by hea3ven** [comment]
In the config directory there should be a asmtweaks.conf file, check if the non-solid leaves tweak is enabled there.

**Comment by K4N0** [comment]
#Fri Oct 30 18:47:08 MST 2015
NonSolidLeaves.enabled=false

Checked the server and the client. They both look like this.

**Comment by K4N0** [comment]
Under Hardmode tweaks config

# Enable tweak to make leaves blocks non-solid (like vines).

```
B:enableNonSolidLeaves=false
```

Checked the server and the client. They both look like this.

edit
Odd font...??

**Comment by K4N0** [comment]
it does the same thing in single player, i'm going to remove all other mods.

**Comment by K4N0** [comment]
Removed all other mods, it does not happen. It works fine. Seems to be another mod compatibility.
i'll start removing mods to see which one is causing this.

**Comment by K4N0** [comment]
Never mind, it seems to have been a glitch of some sort on my client side.
I had done a clean install on the server last attempt but i did not on the client.

I just did a clean install on the client and server and everything is working as it should with all the mods i have in the modpack. Thank You For Everything!!
