### ISSUE TITLE
Non-solid leaves Bug

### ISSUE THREAD

**Issue by Tsyklop** [hea3ven/HardModeTweaks#5]
![2016-02-08_19 11 09](https://cloud.githubusercontent.com/assets/6783568/12893258/d8537010-ce98-11e5-8525-824b79a2e36a.png)

**Comment by hea3ven** [comment]
What minecraft version is this happening on?, also are you using fast graphics?

**Comment by Tsyklop** [comment]
@hea3ven 1.7.10. Yes.

**Comment by Tsyklop** [comment]
@hea3ven I set "Fancy" graphics and all fine. But can you fix this bug?

**Comment by hea3ven** [comment]
Not sure, I might be able to make leaves blocks solid if graphics is set on fast, but it's not easy. This isn't an issue in 1.8 fortunately.

**Comment by Tsyklop** [comment]
@hea3ven I understand that it is hard. But 1.8 is not worth it to move to it. I can not demand from you that you have corrected it. You know better. I will be glad to any your decision.

**Comment by RCXcrafter** [comment]
I have this issue too.

Somehow, if you wait long enough, the entire leaf block will render like it should.
[before](http://imgur.com/twchwoH.png)
[after a while](http://imgur.com/USGHDCi.png)
(do note that I have a whole bunch of other mods too, I have not tested this on its own)

Do you think it would be possible to make all sides of the leaf blocks render at all time?
