### ISSUE TITLE
Food items have massive saturation

### ISSUE THREAD

**Issue by WolfieWaffle** [hea3ven/HardModeTweaks#8]
For whatever reason, when using this mod with AppleCore, the saturation of food items is multiplied, leading to the food having more saturation than actual food value. I'm unsure if this issue appears without AppleCore installed, as AppleCore is what allows me to see the saturation values.

**Comment by hea3ven** [comment]
Are you sure it's not what it's configured? the default config changes food values/saturation to balance against the change in the regeneration.

**Comment by WolfieWaffle** [comment]
Ah I suppose it is. Saw the apple was at 5.2 not 2.4. I didn't expect that, but now that I look at the numbers that's what it is.
